### ISSUE TITLE
pre and post actions for benching

### ISSUE THREAD

**Issue by Jackojc** [martinus/nanobench#22]
I'd like to be able to perform some action before/after an iteration which doesn't get counted towards the runtime. For example, I want to copy an array before each iteration so it starts from a clean slate but I also do not want to measure the runtime of the copying.

**Comment by martinus** [comment]
I have explicitly not added that feature because most of the time this leads to very bad measurement accuracy. If whatever you are measuring is quite fast and each iteration you start and stop the timer, the results will be very unreliable and inaccurate. 

You get better results when you make sure that going to the clean slate is relatively fast compared to what you are measuring, or you perform two benchmarks: one that has the overhead plus what you want to measure, and another benchmark with just the overhead. Then subtract the benchmark results for the overhead and you get the actual result.

**Comment by martinus** [comment]
See #86
