### ISSUE TITLE
[feature] single run benchmarks

### ISSUE THREAD

**Issue by pioneer19** [martinus/nanobench#34]
All microbenchmark software run code under benchmark in loop. This will lead CPU running with all instructions are hot, cached with microcode commands, predictions known for 1M iterations ahead...

My Feature request is to add some single run tests with getting time from rdtsc before common benchmark.

- first run when code is cold will produce cold TimeStamp Counter
- second and third run the same code (with data and instructions cached) and get two hot TSC

Next run current benchmark.

Benchmark statistics need include cold and two hot tsc for each test.

This three numbers (cold and two hot runs) will provide information about times for cold code run (first run when instructions not in CPU cache) and running cached instructions (and data). Two cold numbers will allow evaluate jitter. This numbers will be not so accurate as running code 1M times and get dispersion, but it will provide useful information for running times without trained predictor.

**Comment by Lectem** [comment]
Note that benchmark.net has 'Run startegies' for such things, including a ColdStart one. https://benchmarkdotnet.org/articles/guides/choosing-run-strategy.html#sample-introcoldstart

I wouldn't rely on things like cold start too much for microbenchmarking though, there are way too many things that can happen (or not) for the first (warm-up) iterations.

I think it's OK when you know your code relies on it, for example if you have a cache, but CPUs and OSes make measuring cold start way too hard nowadays, you wouldn't get anything reliable from those results.
Even if you evicted instruction/data caches, branch predictors would always be in a somewhat unknown state, maybe your memory page was not committed yet by the OS etc etc.  Hell, even ASLR or working directory could change those due to code alignment. In any case you would have to run the benchmark multiple times for the results to be reliable, so you would need a way to make the code and data cold again.

**Comment by martinus** [comment]
You can already benchmark a single iteration with this:

```
ankerl::nanobench::Benc().epochs(1).epochIterations(1).run("cold", [&] {
    /* whatever */ 
});
```

So I don't think any special handling is required
